/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class IdMapIndex {
  /**
   * Omitting `dim` constructs a lazy index that locks its dimensionality on
   * the first `addWithIds`. `bitWidth` defaults to 4 and must be in {2,3,4}.
   */
  constructor(dim?: number | undefined | null, bitWidth?: number | undefined | null)
  /**
   * Add `vectors.length / dim` vectors with matching external uint64 `ids`
   * (length = vector count). `dim` is required only on the first add to a
   * lazy index. Rejects duplicate or length-mismatched ids.
   */
  addWithIds(vectors: Float32Array, ids: BigUint64Array, dim?: number | undefined | null): void
  remove(id: bigint): boolean
  /**
   * Top-`k` search returning external uint64 `ids`. `allowlist`, when given,
   * restricts results to those ids; it must be non-empty and every id must
   * be present (else this throws). Result count is `min(k, allowed)`.
   */
  search(queries: Float32Array, k: number, allowlist?: BigUint64Array | undefined | null): IdSearchResult
  contains(id: bigint): boolean
  prepare(): void
  write(path: string): void
  static load(path: string): IdMapIndex
  get dim(): number | null
  get bitWidth(): number
  get length(): number
}

export declare class TurboQuantIndex {
  /**
   * Omitting `dim` constructs a lazy index that locks its dimensionality
   * on the first `add`. `bitWidth` defaults to 4 and must be in {2,3,4}.
   */
  constructor(dim?: number | undefined | null, bitWidth?: number | undefined | null)
  /**
   * Add a flat row-major batch of `vectors.length / dim` vectors. `dim` is
   * required only on the first add to a lazy index; otherwise the locked
   * dim is used and a mismatch is rejected.
   */
  add(vectors: Float32Array, dim?: number | undefined | null): void
  /**
   * Top-`k` search over `queries.length / dim` flat queries. `mask`, when
   * given, is a 0/1 byte array of length `this.length`; only slots set to 1
   * are eligible and the per-query count becomes `min(k, ones)`. Returns
   * flat `scores`/`indices` of length `nq * k`.
   */
  search(queries: Float32Array, k: number, mask?: Uint8Array | undefined | null): SearchResult
  prepare(): void
  /**
   * O(1) deletion that swaps the last vector into slot `idx`, so ordering
   * is not preserved. Returns the moved vector's old index.
   */
  swapRemove(idx: number): number
  write(path: string): void
  static load(path: string): TurboQuantIndex
  get dim(): number | null
  get bitWidth(): number
  get length(): number
}

export interface IdSearchResult {
  scores: Float32Array
  ids: BigUint64Array
  nq: number
  k: number
}

export interface SearchResult {
  scores: Float32Array
  indices: BigInt64Array
  nq: number
  k: number
}
